# Let's Build a Quant Trading Strategy

In [ ]:
# signal = model(x)
# orders = strategy(signal)
# execute(orders)

In [ ]:
# In the last video, we built a model that predicts what the log return will be eight hours from now.

In [ ]:
# Key Questions

# 1. Entry/exit timing
# 2. Trade Size
# 3. Use Leverage?
# 4. Use take-profit orders?
# 5. Use stop-loss orders?



In [ ]:
## the key goal is we want to create a strategy that increases profits from the model's edge

### import the libraries

In [2]:
# Data and analysis libraries
import polars as pl                         # Fast dataframes for financial data
import numpy as np                          # Numerical computing library
from datetime import datetime, timedelta    # Date and time operations
import random


# Machine learning libraries  
import torch                                # PyTorch framework
import torch.nn as nn                       # Neural network modules
import torch.optim as optim                 # Optimization algorithms
import research                             # Model building and training utilities


# Visualization and 
import altair as alt                        # Interactive visualization library

# data sources
import binance                              # Binance market data utilities


### load the model 

In [5]:
import models
model = models.LinearModel(1)
# security alert 
model.load_state_dict(torch.load('model_weights.pth', weights_only=True))
model.eval()

LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

### model parameters

In [6]:
research.print_model_params(model)

linear.weight:
[[-0.09911217]]
linear.bias:
[0.00059838]


In [7]:
def model(x):
    w, b = -0.09911217, 0.00059838
    return w * x + b

model(-0.015) 

0.00208506255

In [8]:
model(0.02) 

-0.0013838634

In [11]:
torch.randn(1) 

tensor([1.6421])

In [ ]:

def nn_model(x):
    x = torch.tensor([x])
    W = torch.tensor([0.08035, -0.01478, -0.03523,  0.06777,  0.03789,  0.0013991, -0.13303,  0.8045])
    b = torch.tensor([0.16421])
    return torch.relu(torch.sum(x * W) + b)

nn_model(-0.015)

tensor([0.1521])

In [ ]:
# no interability
nn_model(0.02)

tensor([0.1804])