# Let's Build a Quant Trading Strategy - Part 3

In [1038]:
# y_hat = model(x)
# orders = strategy(y_hat)
# execute(orders)

In [1039]:
# 1st video = Research
# 2nd video = Strategy
# 3rd video = Implementation

# I strongly recommend to watch the first and second video (but I must warn you that they are long videos!)

In [1040]:
# By the end of this video, we will have coded everything all together and put it live!
# Put it live with real money and see what happens.
# I will do a follow up video to see how it performs. 
# Even if it doesn't perform as expected, we can learn from it. 
# We might experience model drift - where where the pattern it learned starts to no longer hold true. 
# You might hear this be called alpha decay - which is your profits decay because of model drift. 
# So even if the pattern lose persistence; we can learn from it. For example, using sliding window instead and retrain.


Goals:

1. Code it all together and put it live.
2. Show you how to build the architecture of a trading system 
3. Learn how to stream exchange data efficiently and react to events.

In [1041]:
# This will video will be more software engineering now as we have to code it all together.

# 1. Ability to stream data from the exchange efficiently - just like Netflix - 
# Netflix intelligently buffers the data - you never have to wait for Netflix to download the next scenes - it's all seamless
# Our system needs to stream data seamlessly
# Our system needs to react to the prices - events
# Our system needs to handle events


## Recap

### Part 1: Research

In [1042]:
import models
import torch
import research

model = models.LinearModel(3)
# security alert 
model.load_state_dict(torch.load('model_weights.pth', weights_only=True))
model.eval()

LinearModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)

### AR(3) Model - 12h forecast horizon

In [1043]:
research.print_model_params(model)

linear.weight:
[[-0.10395038 -0.06726477  0.02827305]]
linear.bias:
[0.00067121]


### Part 2: Strategy Recap

In [1044]:
# Showed a strategy that generates ~14% without any optimization.
# I then showed used some strategy decisions that turned that 14% to >40% optimization 
# The reason for the huge increase in returns were a combination:
# 1. Model's statistical edge 2. Compounding Trade Sizing 3. Leverage



## The fundamental building block: Tick

In [1045]:
from abc import ABC, abstractmethod
from typing import Generic, TypeVar

T = TypeVar('T')  # input type
R = TypeVar('R')  # output type

class Tick(ABC, Generic[T, R]):
    @abstractmethod
    def on_tick(self, val: T) -> R:
        """Handle a new tick and optionally return a result."""
        pass

## The fundamental data structure: Window

In [1046]:
from collections import deque
from typing import Deque, Optional

class DequeWindow(Tick[T, Optional[T]], Generic[T]):
    def __init__(self, n: int):
        self._data: Deque[T] = deque(maxlen=n)

    def on_tick(self, val: T) -> Optional[T]:
        """Append a value and return the oldest value dropped (if any)."""
        dropped = None
        if len(self._data) == self.capacity():
            dropped = self._data[0]
        self._data.append(val)
        return dropped

    def capacity(self) -> int:
        n = self._data.maxlen
        return 0 if n is None else n
    
    def is_full(self) -> bool:
        return self._data.maxlen == len(self._data)
    
    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        return f"{cls_name}(capacity={self._data.maxlen}, values={list(self._data)})"

### Streaming Example: Sliding Window

In [1047]:
w = DequeWindow(3)
w.on_tick(1)
w

DequeWindow(capacity=3, values=[1])

In [1048]:
w = DequeWindow(3)
w.on_tick(1)
w.on_tick(2)
w

DequeWindow(capacity=3, values=[1, 2])

In [1049]:
w = DequeWindow(3)
w.on_tick(1)
w.on_tick(2)
w.on_tick(3)
w


DequeWindow(capacity=3, values=[1, 2, 3])

In [1050]:
w = DequeWindow(3)
w.on_tick(1)
w.on_tick(2)
w.on_tick(3)
old_v = w.on_tick(4)

(old_v, w)

(1, DequeWindow(capacity=3, values=[2, 3, 4]))

In [1051]:
w = DequeWindow(3)
w.on_tick(1)
w.on_tick(2)
w.on_tick(3)
w.on_tick(4)
old_v = w.on_tick(5)

(old_v, w)

(2, DequeWindow(capacity=3, values=[3, 4, 5]))

### Array-based Window

In [1052]:
import numpy as np
from typing import Optional

class NumpyWindow(Tick[T, Optional[T]]):
    """Fixed-capacity sliding window for scalar values using a NumPy array (shift on append)."""

    def __init__(self, n: int, dtype=np.float64):
        if n <= 0:
            raise ValueError("Capacity must be positive.")
        self._capacity = n
        self._data = np.zeros(n, dtype=dtype)
        self._size = 0

    def on_tick(self, val: float) -> Optional[float]:
        """
        Append a scalar value and return the oldest value dropped (if any).
        """
        val = float(val)
        dropped = None

        if self._size < self._capacity:
            self._data[self._size] = val
            self._size += 1
        else:
            # buffer full: drop oldest and shift left
            dropped = self._data[0]
            self._data[:-1] = self._data[1:]  # shift left
            self._data[-1] = val

        return dropped

    def append_left(self, val: float) -> Optional[float]:
        """
        Append a scalar value to the **front** (left) of the buffer.
        Shifts all elements right by one and drops the newest (rightmost) if full.
        """
        val = float(val)
        dropped = None

        if self._size < self._capacity:
            # Shift right only the valid region
            if self._size > 0:
                self._data[1:self._size + 1] = self._data[:self._size]
            self._data[0] = val
            self._size += 1
        else:
            # Drop newest (rightmost) value
            dropped = self._data[self._size - 1]
            self._data[1:] = self._data[:-1]  # shift right
            self._data[0] = val

        return dropped

    def __getitem__(self, idx: int) -> float:
        """Index access (0 = oldest)."""
        if not 0 <= idx < self._size:
            raise IndexError("Index out of range.")
        return self._data[idx]

    def __len__(self) -> int:
        return self._size

    def capacity(self) -> int:
        return self._capacity

    def is_full(self) -> bool:
        return self._size == self._capacity

    def values(self) -> np.ndarray:
        """Return current valid values as a contiguous 1D array (no copy needed)."""
        return self._data[:self._size]

    def __repr__(self) -> str:
        vals = self.values().tolist()
        return f"{self.__class__.__name__}(capacity={self._capacity}, size={self._size}, values={vals})"


### Streaming Example: Numpy Sliding Window

In [1053]:
w = NumpyWindow(3)
w.on_tick(1)
w

NumpyWindow(capacity=3, size=1, values=[1.0])

In [1054]:
w = NumpyWindow(3)
w.on_tick(1)
w.on_tick(2)
w

NumpyWindow(capacity=3, size=2, values=[1.0, 2.0])

In [1055]:
w = NumpyWindow(3)
w.on_tick(1)
w.on_tick(2)
w.on_tick(3)
w

NumpyWindow(capacity=3, size=3, values=[1.0, 2.0, 3.0])

In [1056]:
w = NumpyWindow(3)
w.on_tick(1)
w.on_tick(2)
w.on_tick(3)
v = w.on_tick(4)
(v, w)

(np.float64(1.0), NumpyWindow(capacity=3, size=3, values=[2.0, 3.0, 4.0]))

### Streaming the Last Known Value (To Track Close Price)

In [1057]:
class Last(Tick[T, T], Generic[T]):
    def __init__(self):
        self._value: Optional[T] = None

    def on_tick(self, val: T) -> Optional[T]:
        """Append a value and return the oldest value dropped (if any)."""
        self._value = val
        return val

    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        return f"{cls_name}(value={self._value})"

### Streaming Example: Last Value

In [1058]:
last_val = Last()
last_val

Last(value=None)

In [1059]:
last_val = Last()
last_val.on_tick(1)
last_val.on_tick(2)
last_val.on_tick(3)
last_val

Last(value=3)

### Streaming Log Returns

#### Quick Log Returns Recap

In [1060]:
portfolio_values = [100, 120, 100]
log_returns = [
    np.log(portfolio_values[1]/portfolio_values[0]), 
    np.log(portfolio_values[2]/portfolio_values[1]), 
]
log_returns

[np.float64(0.1823215567939546), np.float64(-0.1823215567939546)]

In [1061]:
np.sum(log_returns)

np.float64(0.0)

In [1062]:

import numpy as np

class LogReturn(Tick[float, float], Generic[T]):
    def __init__(self):
        self._window = NumpyWindow(2)

    def on_tick(self, val: float) -> Optional[float]:
        self._window.on_tick(val)
        if self._window.is_full():
            return np.log(self._window[1] / self._window[0])
        else:
            return None
        
    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        return f"{cls_name}(window={self._window})"        
    

### Streaming Example: Log Returns

In [1063]:
f = LogReturn()
f.on_tick(90.0)
f

LogReturn(window=NumpyWindow(capacity=2, size=1, values=[90.0]))

In [1064]:
f = LogReturn()
f.on_tick(90.0)
v = f.on_tick(100.0)
(v, f)

(np.float64(0.10536051565782635),
 LogReturn(window=NumpyWindow(capacity=2, size=2, values=[90.0, 100.0])))

In [1065]:
np.log(100/90)

np.float64(0.10536051565782635)

In [1066]:
f = LogReturn()
f.on_tick(90.0)
f.on_tick(100.0)
v = f.on_tick(150.0)
(v, f)

(np.float64(0.4054651081081644),
 LogReturn(window=NumpyWindow(capacity=2, size=2, values=[100.0, 150.0])))

In [1067]:
np.log(150/100)

np.float64(0.4054651081081644)

### Streaming Auto-Regressive Log Returns Lags

#### Auto-Regression Recap

In [1068]:
time_series = [0.1, -0.2, -0.3]
lag_1 = time_series[-1]
lag_1

-0.3

In [1069]:
lag_1 = time_series[-2]

In [1070]:

class LogReturnLags(Tick[float, torch.Tensor]):
    def __init__(self, no_lags: int):
        self._lags = NumpyWindow(no_lags)
        self._log_return = LogReturn()
    
    def on_tick(self, val: float) -> torch.Tensor | None:
        log_ret = self._log_return.on_tick(val)
        if log_ret is not None:
            self._lags.append_left(log_ret)
            return torch.tensor(self._lags.values(), dtype=torch.float32) if self._lags.is_full() else None
        else:
            return None
        
    def __repr__(self) -> str:
        cls_name = self.__class__.__name__
        return f"{cls_name}(lags={self._lags}, log_return={self._log_return})" 

### Streaming Example: Auto-Regressive Log Returns

In [1071]:
lags = LogReturnLags(3)
v = lags.on_tick(90)
v

In [1072]:
lags = LogReturnLags(3)
lags.on_tick(90)
lags.on_tick(100)


In [1073]:
lags = LogReturnLags(3)
lags.on_tick(90)
lags.on_tick(100)
lags.on_tick(150)

In [1074]:
lags = LogReturnLags(3)
lags.on_tick(90)
lags.on_tick(100)
lags.on_tick(150)
lags.on_tick(110)

tensor([-0.3102,  0.4055,  0.1054])

In [1075]:
lags = LogReturnLags(3)
lags.on_tick(90)
lags.on_tick(100)
lags.on_tick(150)
lags.on_tick(110)
features = lags.on_tick(160)
features

tensor([ 0.3747, -0.3102,  0.4055])

### Example: Streaming the Features into our Model 

In [1076]:
import models
model = models.LinearModel(3)
# security alert 
model.load_state_dict(torch.load('model_weights.pth', weights_only=True))
model.eval()

LinearModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)

In [1077]:
X = torch.tensor(features, dtype=torch.float32)
X

/var/folders/76/9jsfkv6171g18thlymfk4w200000gn/T/ipykernel_60492/487570526.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(features, dtype=torch.float32)


tensor([ 0.3747, -0.3102,  0.4055])

In [1078]:
y_hat = model(X)
y_hat

tensor([-0.0060], grad_fn=<ViewBackward0>)

In [1079]:
y_hat[0]

tensor(-0.0060, grad_fn=<SelectBackward0>)

### Build The Trading System

In [1080]:
from decimal import Decimal
from typing import Dict, List
from dataclasses import dataclass
import torch.nn as nn
import polars as pl

@dataclass(frozen=True)
class Order:
    sym: str
    signed_val: Decimal

    def __str__(self) -> str:
        sign = "BUY" if self.signed_qty > 0 else "SELL"
        return f"Order({sign} {abs(self.signed_val)} {self.sym})"

@dataclass(frozen=True)
class Trade:
    sym: str
    signed_qty: Decimal
    price: Decimal
    value: Decimal

    def __str__(self) -> str:
        sign = "BUY" if self.signed_qty > 0 else "SELL"
        return f"Trade({sign} {abs(self.signed_qty)} {self.sym} {self.price})"


@dataclass
class Position:
    sym: str
    signed_qty: Decimal
    price: Decimal

    def close(self) -> "Order":
        return Order(self.sym, -self.signed_qty)


### Create Base Class for Market

In [1081]:
from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Dict

class Account(ABC):
    """Abstract base class representing a trading account."""

    @abstractmethod
    def balance(self) -> Decimal:
        """Return the current account balance."""
        pass

    @abstractmethod
    def market_order(self, sym: str, qty: Decimal, price: Decimal = None) -> "Trade":
        """Execute a market order and return a Trade result."""
        pass

    @abstractmethod
    def positions(self) -> Dict[str, "Position"]:
        """Return current open positions."""
        pass




### Create Test Account

In [1082]:
from decimal import Decimal
from typing import Dict, Optional

class TestAccount(Account):
    """A simulated account for testing or paper trading."""

    def __init__(self, time_series: pl.DataFrame, starting_balance: Decimal) -> None:
        self._balance = starting_balance
        self.time_series = time_series
        self._positions: Dict[str, Position] = {}
        self.counter: int = 0

    def balance(self) -> Decimal:
        return self._balance

    def get_trade_price(self) -> Decimal:
        price = self.time_series["close"][self.counter]
        self.counter += 1
        return Decimal(price)

    def market_order(self, sym: str, value: Decimal, price: Decimal = None) -> "Trade":
        # Simulate a fill at fixed price
        if price is None:
            price = self.get_trade_price()
        qty = value / price
        
        # Update balance and position
        self._balance -= value
        self._positions[sym] = Position(sym, qty, price)

        return Trade(sym=sym, signed_qty=qty, price=price, value=qty*price)

    def positions(self) -> Dict[str, "Position"]:
        return self._positions
    
    def close_position(self, sym: str) -> Optional[Trade]:
        position = self._positions.pop(sym, None)
        return position.close() if position else None

    def __repr__(self) -> str:
        return f"TestAccount(balance={self._balance}, positions={list(self._positions.keys())})"


### Test Market Order in Test Account

In [1083]:
time_series = pl.read_csv('BTCUSDT_12h_ohlc.csv', try_parse_dates=True)
time_series

shape: (692, 5)
┌─────────────────────┬──────────┬──────────┬──────────┬──────────┐
│ datetime            ┆ open     ┆ high     ┆ low      ┆ close    │
│ ---                 ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ datetime[μs]        ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════════════╪══════════╪══════════╪══════════╪══════════╡
│ 2024-10-29 00:00:00 ┆ 69939.9  ┆ 71607.0  ┆ 69733.0  ┆ 71440.1  │
│ 2024-10-29 12:00:00 ┆ 71440.0  ┆ 73660.0  ┆ 70900.0  ┆ 72739.5  │
│ 2024-10-30 00:00:00 ┆ 72739.5  ┆ 72797.4  ┆ 71931.1  ┆ 71995.0  │
│ 2024-10-30 12:00:00 ┆ 71994.9  ┆ 72984.9  ┆ 71444.2  ┆ 72349.0  │
│ 2024-10-31 00:00:00 ┆ 72349.0  ┆ 72720.3  ┆ 72030.5  ┆ 72213.3  │
│ …                   ┆ …        ┆ …        ┆ …        ┆ …        │
│ 2025-10-07 12:00:00 ┆ 124397.1 ┆ 125098.0 ┆ 120516.0 ┆ 121286.5 │
│ 2025-10-08 00:00:00 ┆ 121286.6 ┆ 123150.0 ┆ 121005.3 ┆ 122825.7 │
│ 2025-10-08 12:00:00 ┆ 122825.8 ┆ 124170.6 ┆ 121607.8 ┆ 123237.5 │
│ 2025-10-09 00:00:00 ┆ 123237.4 ┆ 123279.7 ┆ 121081.5 ┆ 122672.9 │
│ 2025-10-09 12:00:00 ┆ 122673.0 ┆ 123740.1 ┆ 119572.8 ┆ 121579.3 │
└─────────────────────┴──────────┴──────────┴──────────┴──────────┘

In [1084]:
# place market order
acc = TestAccount(time_series, Decimal(100.0))
acc.market_order('BTCUSDT', Decimal(100.0))

Trade(sym='BTCUSDT', signed_qty=Decimal('0.001399774076464058586875473581'), price=Decimal('71440.10000000000582076609134674072265625'), value=Decimal('100.0000000000000000000000000'))

### Develop Strategy API

In [ ]:

class Strategy(ABC):
    """Abstract base class representing a trading account."""

    @abstractmethod
    def on_tick(self, price: float, account: Account) -> List[Order] | None:
        pass

class BasicTakerStrat(Strategy):
    def __init__(self, 
                 sym: str,
                 model: nn.Module, 
                 log_return_lags: LogReturnLags, 
                 scale_factor: Decimal = None) -> None:
        self.sym = sym
        self.model = model
        self.log_return_lags = log_return_lags
        if scale_factor is None:
            scale_factor = Decimal(1.0)
        self.scale_factor = scale_factor

    def _signed_trade_size(self, y_hat: float, account: Account) -> Decimal:
        dir_signal = np.sign(y_hat)
        balance =  account.balance()
        print(balance)
        v = Decimal(dir_signal) * balance
        return v * self.scale_factor

    def _create_orders(self, y_hat: torch.Tensor, account: Account) -> List[Order]:
        print(y_hat)
        not_val = self._signed_trade_size(y_hat.item(), account)
        open_order = Order(self.sym, not_val)
        close_order = account.close_position(self.sym)
        print(close_order)
        orders = [close_order, open_order] if close_order else [open_order]
        return orders      

    def on_tick(self, price: float, account: Account) -> List[Order] | None:
        X = self.log_return_lags.on_tick(price)
        if X is not None:
            with torch.no_grad():
                print(X)
                y_hat = self.model(X)
                orders = self._create_orders(y_hat, account)
                return orders
        return None

In [1086]:
sym = 'BTCUSDT'
lags = LogReturnLags(3)
acc = TestAccount(time_series, Decimal(100.0))

strat = BasicTakerStrat(sym, model, lags, Decimal(1.0))
strat.on_tick(100.0, acc)
strat.on_tick(110.0, acc)
strat.on_tick(90.0, acc)
orders = strat.on_tick(105, acc)
orders

tensor([ 0.1542, -0.2007,  0.0953])


TypeError: BasicTakerStrat._create_orders() missing 1 required positional argument: 'price'

In [ ]:
x = [np.log(105/90), np.log(90/110.0), np.log(110/100)]
x

In [ ]:
import research
research.print_model_params(model)

In [ ]:
w = np.array([-0.10395038, -0.06726477,  0.02827305]) 
w

In [ ]:
b = 0.00067121
np.dot(w,x) + b

In [ ]:
lags = LogReturnLags(3)
acc = TestAccount(time_series, Decimal(100.0))

strat = BasicTakerStrat(sym, model, lags, Decimal(1.0))
strat.on_tick(100.0, acc)
strat.on_tick(110.0, acc)
strat.on_tick(90.0, acc)
orders = strat.on_tick(105, acc)
acc.market_order(sym,  orders[0].signed_qty, Decimal(105))
strat.on_tick(120, acc)

### Time Interval Timer - 12h

In [ ]:
from datetime import datetime, timezone

def epoch_now():
    return datetime.now(timezone.utc).timestamp()

epoch_utc = epoch_now()
epoch_utc

In [ ]:
def ts_bar(epoch: float | int, n: int) -> int:
    epoch = int(epoch)
    return epoch - (epoch % n)

In [ ]:
min_in_secs = 60

In [ ]:
ts_bar(epoch_utc, min_in_secs)

In [ ]:
ts_bar(epoch_utc + 61, min_in_secs)

In [ ]:
class IntervalTimer(Tick[int, bool]):
    def __init__(self, interval_mins: int):
        self.last_bar: int = 0  
        self.time_interval = interval_mins * 60

    def on_tick(self, epoch: int) -> bool:
        bar = ts_bar(epoch, self.time_interval)
        if bar > self.last_bar:
            self.last_bar = bar
            return True
        return False

### Timer Example

In [ ]:
timer = IntervalTimer(1)

now = epoch_now()

timer.on_tick(now)

In [ ]:
timer.on_tick(now + 2)

In [ ]:
timer.on_tick(now + 60)

In [ ]:
timer.on_tick(now + 60)

In [ ]:
### Execution

In [ ]:
# y_hat = model(x)
# orders = strategy(y_hat)
# execute(orders)

In [ ]:
import asyncio

class TestExecutionEngine:
    def __init__(self, time_series: pl.DataFrame, strat: Strategy, timer: IntervalTimer, account: TestAccount):
        self.time_series = time_series
        self.strat: Strategy = strat
        self.timer: IntervalTimer = timer
        self.account: TestAccount = account
        self.counter: int = 0
    
    async def _execute(self, orders: List["Order"]):
        """Execute orders asynchronously (can simulate latency, slippage, etc)."""
        
        if not orders:
            await asyncio.sleep(0.01)
        return


    async def start(self):
        """Run main event loop asynchronously."""
        print("Execution engine started...")
        while True:
            # now = epoch_now()

            # if not self.timer.on_tick(now):
            #     await asyncio.sleep(0.01)
            #     continue
            await asyncio.sleep(5.0)

            if self.counter >= len(self.time_series):
                return
            
            close_price = float(self.time_series["close"][self.counter])
            print(f"{self.counter}: {close_price}")
            self.counter += 1
            orders = self.strat.on_tick(close_price, self.account)

            await self._execute(orders)
    



In [ ]:
import asyncio

sym = 'BTCUSDT'
lags = LogReturnLags(3)
strat = BasicTakerStrat(sym, model, lags, 1.0)
time_series = pl.read_csv('BTCUSDT_12h_ohlc.csv', try_parse_dates=True)
timer = IntervalTimer(60 * 12)
account = TestAccount(time_series, Decimal(100.0))

engine = TestExecutionEngine(time_series, strat, timer, acc)

async def main():
    print("Start...")

    await engine.start()
    print("Done!")

# You can directly await
await main()